import { createEventEnvelope, EventEnvelope } from '../../monetization/core/EventEnvelope';
import { InMemoryEventBus } from '../../monetization/core/InMemoryEventBus';

export interface AutoGeneratedContent {
  readonly contentId: string;
  readonly productId: string;
  readonly title: string;
  readonly body: string;
}

export class AutoContentGenerator {
  constructor(private readonly eventBus: InMemoryEventBus) {}

  public async generateFromRelease(productId: string, releaseVersion: string): Promise<AutoGeneratedContent> {
    const content: AutoGeneratedContent = {
      contentId: `cnt_${productId}_${releaseVersion}`,
      productId,
      title: `Release ${releaseVersion} is live`,
      body: `Automated release summary for ${productId} on version ${releaseVersion}.`
    };

    const event: EventEnvelope<Record<string, unknown>> = createEventEnvelope(
      'content.generated',
      'AutoContentGenerator',
      {
        contentId: content.contentId,
        productId: content.productId
      }
    );

    await this.eventBus.publish(event);
    return content;
  }
}
