import { createEventEnvelope, EventEnvelope } from '../../monetization/core/EventEnvelope';
import { InMemoryEventBus } from '../../monetization/core/InMemoryEventBus';
import { AutoGeneratedContent } from './AutoContentGenerator';

export interface AutoPublishedContent {
  readonly publicationId: string;
  readonly contentId: string;
  readonly channels: string[];
}

export class AutoPublisher {
  constructor(private readonly eventBus: InMemoryEventBus) {}

  public async publish(content: AutoGeneratedContent, channels: string[]): Promise<AutoPublishedContent> {
    const publication: AutoPublishedContent = {
      publicationId: `pub_${content.contentId}`,
      contentId: content.contentId,
      channels
    };

    const event: EventEnvelope<Record<string, unknown>> = createEventEnvelope(
      'content.autopublished',
      'AutoPublisher',
      {
        publicationId: publication.publicationId,
        contentId: publication.contentId,
        channels: publication.channels
      }
    );

    await this.eventBus.publish(event);
    return publication;
  }
}
